--- 
title: "Modul Pelatihan JNE"
subtitle: "Data Analytics With Phyton (Beginner)"
author: "Penulis: Bakti Siregar, S.Si.,M.Sc"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: docs
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: sainzdata/Py_JNE
description: "Materi ini diperuntukkan untuk pelatihan Analisis Data dengan menggunakan Python di JNE"
---

# Overview {-}

Placeholder


## Jadwal Pelatihan 
## Kewajiban & Hak Peserta
## Tim Penyusun & Pemateri

<!--chapter:end:index.Rmd-->


# Pengenalan Python? {-}

Placeholder


## Sejarah
## Peranan 
## Keunggulan
## Instalasi
### Windows 
### Macintosh
### Linux
## Teks Editor

<!--chapter:end:00-Pengenalan_Python.Rmd-->


# Konsep Dasar Python

Placeholder


## Atribut & Peralatan
### Objek 
### Variabel 
### Statement
### Komentar 
## Persiapan
### Tipe Data
### Operator 
#### Operator Penugasan  {-}
#### Operator Aritmatika {-}
#### Operator Pembanding {-}
#### Opeartor Logika  {-}
## Proses (Algoritma)
### Percabangan If
### Percabangan If/Else
### Percabangan If/Elif/Else
### Perulangan for
### Perulangan while
## Penyajian

<!--chapter:end:01_Konsep_Dasar_Python.Rmd-->


# Persiapan Data

Placeholder


## Tahapan Persiapan Data
## Mengapa Python vs Excel?
## Contoh Persiapan Data 1
### Impor Data 
#### Excel {-}
#### Python {-}
### Ekspor (Simpan Data)
#### Excel {-}
#### Python {-}
### Menyortir Data
#### Excel {-}
#### Python {-}
### Penjumlahan Nilai di Kolom
#### Excel {-}
#### Python {-}
### Join Data 
#### Excel {-}
#### Python {-}
### Kondisional Nilai
#### Excel {-}
#### Python {-}
### Tabel pivot
#### Excel {-}
#### Python {-}
## Contoh Persiapan Data 2
## Persiapan Data Lanjutan
### Import Data
### Format Tanggal
### Rename Variabel
### Ekspor Data
### Ekstrak Kondisional Data
### 8 Baris Pertama (Tugas)
### Check Dimensi Data (Tugas)
### Check Atribut Kolom (Tugas)
### Info Dasar Data (Tugas)
### Pembulatan Nilai (Tugas)
### Pilah Data Kolom (Tugas)
###  Kolom Baru (Tugas)
### Sortir Data
### Tabel Pivot 

<!--chapter:end:02-Persiapan_Data.Rmd-->


# Visualisasi Data

Placeholder


## Import Data
## Verifikasi Kelengkapan Data
## Perbaharui Data
### Quiz 1 {-} 
### Quiz 2  {-}
## Statistik Dasar
### Quiz 3 {-}
### Quiz 4 {-}
## Tabel Pivot
### Quiz 5 {-}
### Quiz 6 {-}
## Pie-Chart
### Quiz 7 {-}
## Bar-Chart
### Quiz 8 {-}
## Box-plot 
## Scatter Plot 
## Diagram Garis

<!--chapter:end:03-Visualisasi_Data.Rmd-->

# Pemodelan

Materi masih dalam proses pengembangan oleh Tim


```{python}
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

app = Dash(Bakti) 


app.layout = html.Div([
    html.H4('Analysis of the restaurant sales'),
    dcc.Graph(id="graph"),
    html.P("Names:"),
    dcc.Dropdown(id='names',
        options=['smoker', 'day', 'time', 'sex'],
        value='day', clearable=False
    ),
    html.P("Values:"),
    dcc.Dropdown(id='values',
        options=['total_bill', 'tip', 'size'],
        value='total_bill', clearable=False
    ),
])


@app.callback(
    Output("graph", "figure"), 
    Input("names", "value"), 
    Input("values", "value"))
def generate_chart(names, values):
    df = px.data.tips() # replace with your own data source
    fig = px.pie(df, values=values, names=names, hole=.3)
    return fig


app.run_server(debug=True)
```


<!--chapter:end:04-Pemodelan.Rmd-->

# Studi Kasus

Materi masih dalam proses pengembangan oleh Tim

<!--chapter:end:05-Studi_Kasus.Rmd-->

`r if (knitr:::is_html_output()) '
# Referensi {-}
'`

##  Pertemuan 1 {-}

1.    https://www.tutorialspoint.com/r/index.htm
2.    https://www.statista.com/chart/16567/popular-programming-languages/
3.    https://www.anotherbookondatascience.com/chapter1.html
4.    https://www.kodefungsi.com/fungsi/PYTHON/
5.    https://www.anotherbookondatascience.com/chapter1.html
6.    https://www.petanikode.com
7.    https://stiki-indonesia.ac.id/2021/03/23/perkembangan-python-dan-alasan-sangat-penting-untuk-data-analitik/





<!--chapter:end:06-Referensi.Rmd-->

